services:
  - type: web
    name: mtg-card-sorter
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python update_database.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0